title: Cromattica - A Digital Product Agency
email: miguel@cromattica.com
description: Landing page www.cromattica.com
url: "http://www.cromattica.com"

# Build settings
markdown: kramdown
exclude: ['README.md', 'CNAME', 'Gemfile', 'Gemfile.lock', 'package.json', 'assets/css/vendor']

# Sass settings
sass:
  sass_dir: assets/css
  style: :compressed
